#!/bin/bash

function print_usage {
  echo "Usage: rndstr [-c count] [-f (uln)]"
  echo $'\t-h  \tprint this usage help'
  echo $'\t-c n\tprint <n> characters, default=64'
  echo $'\t-f u\tinclude uppercase letters'
  echo $'\t   l\tinclude lowercase letters'
  echo $'\t   n\tinclude numerals'
}

CHARACTER_COUNT=64
FILTER='a-zA-Z0-9'

while getopts "hc:f:" opt
do
  case $opt in
    h)
      print_usage
      exit 0
      ;;
    c)
      CHARACTER_COUNT=${OPTARG:=64}
      ;;
    f)
      FILTER=''
      for i in $(seq 1 ${#OPTARG})
      do
        case ${OPTARG:i-1:1} in
          u)
            FILTER+='A-Z'
            ;;
          l)
            FILTER+='a-z'
            ;;
          n)
            FILTER+='0-9'
            ;;
        esac
      done
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

function print_random {
  local LC_CTYPE=C
  export LC_CTYPE
  cat /dev/urandom | tr -dc $FILTER | head -c $CHARACTER_COUNT
}

print_random
